package shell

var helpText = `######### bucketstore command line tool help #########
An interactive shell for bucketstore.

Usage:
  <command> [<options...>] [<args...>]


Commands:
  exit                            Exit.
  help                            Show help.

  buckets                         List all buckets.

  put <bucket> <key> <value>      Put a key/value pair item in a bucket.
  post <bucket> <value>           Post a key/value pair item in a bucket
                                  using key that is generated by autoincrementing sequence.
  get <bucket> <key>              Get a item of the key from a bucket.
  delete <bucket> <key>           Delete a item from a bucket.
  delete bucket <bucket>          Delete a bucket.

  select <bucket> <options...>    List items in the bucket.
                                  This command can have some options.
                                  Please see the "Select command options" section.

Global options:
  -p      Output indented json response.

Select command options:
  --offset <number>      Offset of items to get.
  --limit <number>       Limit of items to get.
  --filter <filter>      Filter of selection
  --orderby asc|desc     Sort order.
  --prefix <prefix>      Prefix string.
  --match <match>        Match string or number.
  --min <min>            Min string or number.
  --max <max>            Max string or nubmer.

Examples:
  Post animals to the "zoo" bucket.

    > post 'zoo' '{"name": "joe", "class": "lion", "age": 5}'
    > post 'zoo' '{"name": "foo", "class": "lion", "age": 13}'
    > post 'zoo' '{"name": "coo", "class": "tiger", "age": 6}'
    > post 'zoo' '{"name": "tony", "class": "horse", "age": 2}'

  Show buckets.

    > buckets -p

  Get a animal

    > get 'zoo' 1 -p

  Select all animals

    > select 'zoo' -p

  Select only lions

    > select 'zoo' --filter propValueMatch --prop 'class' --match 'lion' -p

  Select only lions with limit 1

    > select 'zoo' --filter propValueMatch --prop 'class' --match 'lion' --limit 1 -p

  Delete a animal from the zoo.

    > delete 'zoo' 1

  Delete the zoo.

    > delete bucket 'zoo'

Non-interactive mode:
  It support non-interactive mode by using with pipe like the below.

    $ echo "buckets" | bucketstore yourdata.db




`
